name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install operating system dependencies
        run: yarn
      - name: Setup playwright dependencies
        run: yarn playwright install-deps
      - name: Run your tests
        run: yarn playwright test --browser=all
